image: Visual Studio 2017

install:
  - cinst gitversion.portable -pre -y

platform: Any CPU

configuration: Release

assembly_info:
  patch: false

before_build:
  - nuget restore Source/PropertyTools.AppVeyor.sln
  - ps: gitversion /l console /output buildserver
  
build_script:
  - msbuild Source/PropertyTools.AppVeyor.sln /p:Version=%GitVersion_NuGetVersion%

artifacts:
  - path: '**/*.nupkg'
