image: Visual Studio 2017

install:
  - cinst gitversion.portable -pre -y

platform: Any CPU

configuration: Release

assembly_info:
  patch: false

before_build:
  - nuget restore Source/PropertyTools.AppVeyor.sln
  - ps: gitversion /l console /output buildserver
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%GitVersion_NuGetVersion%'
  package_version: '%GitVersion_NuGetVersion%'
  assembly_version: '%GitVersion_NuGetVersion%'
  file_version: '%GitVersion_NuGetVersion%'
  informational_version: '%GitVersion_NuGetVersion%'

build:
  project: Source/PropertyTools.AppVeyor.sln
  verbosity: minimal

artifacts:
  - path: '*.nupkg'
    name: PropertyTools.Wpf-$(GitVersion_SemVer)
    type: zip
