image: Visual Studio 2017

install:
  - cinst gitversion.portable -pre -y

platform: Any CPU

configuration: Release

assembly_info:
  patch: false

before_build:
  - nuget restore Source/PropertyTools.AppVeyor.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  
build:
  project: Source/PropertyTools.AppVeyor.sln
  verbosity: minimal

after_build:
  - cmd: NuGet pack Source\PropertyTools.Wpf\PropertyTools.Wpf.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"

artifacts:
  - path: '*.nupkg'
    name: PropertyTools.Wpf-$(GitVersion_SemVer)
    type: zip
